firstName=input('Enter your firstName:')
lastName=input('Enter your lastName:')
print(f'Your Full name is {firstName} {lastName}')
print(f'Your Initials are {firstName[0]} {lastName[0]}')
print(f'First name length is {len(firstName)} letters')
print(f'Last name length is {len(lastName)} letters')
print(f'Full name length is {len(firstName)+len(lastName)} letters')
print(f'First name starts with {firstName[0]} ')
print(f'First name ends with {firstName[-1]}')
print(f'Last name starts with {lastName[0]}')
print(f'Last name ends with {lastName[-1]}')
print(f'first name indexes are 0-{len(firstName)-1}')
print(f'Last name  indexes are 0-{len(lastName)-1}')
print(f'First name trims 1 {firstName[0:3]}')
print(f'First name trims 2 {firstName[1:]}')
print(f'Last name trims 1 {lastName[0:3]}')
print(f'Last name trims 2 {lastName[3:]}')